#!/bin/bash
# Programs that will run after Openbox has started

~/.bash_profile

trayer --expand true --edge bottom --align right --widthtype request --transparent true --tint black --SetDockType true& 
# trayer --SetDockType false 

# sometimes after launching nautilus, the last one sets blank screen after timeout. i don't need it
# solution from: http://ubuntuforums.org/showthread.php?t=1283057
xset s off
xset -dpms
xset s noblank

setlayout 0 3 3 0

# tiling manager
pytyle2&

if [ -z "$(pgrep workrave)" ]; then
	workrave&
fi

# lal clock
lal &

if [ -z "$(pgrep python)" ]; then
	ipython3 notebook --no-browser --notebook-dir=/home/sypwex/src/python/notebooks 2> /dev/null&
fi

# ALSA/JACK control panel
if [ -z "$(pgrep jackd)" ]; then
	cadence&
fi

# printer manager
if [ -z "$(pgrep system-config-printer-applet)" ]; then
	system-config-printer-applet&
fi

# dash
synapse&

# network manager
if [ -z "$(nm-applet)" ]; then
	nm-applet&
fi

